[package]
name = "ludex-dbus-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
description = "Wire types for the net.ludex.Tracker1 D-Bus API"

[dependencies]
serde = { workspace = true }
zbus = { workspace = true }

[lints]
workspace = true
